### ISSUE TITLE
Warning: Failed prop type: Invalid prop `top` supplied to `View`.

### ISSUE THREAD

**Issue by sant3001** [robcalcroft/react-native-in-app-notification#18]
This warning is poping up in the console every time and it is coming from `src/DefaultNotificationBody/index.ios.js`. On line 14 the code should be changed from:

    top: isIphoneX() && getStatusBarHeight(),
to

    top: isIphoneX() ? getStatusBarHeight() : 0,

**Comment by flown1** [comment]
Thanks a lot for the fix. That warning can be pretty annoying :+1:
