### ISSUE TITLE
Close notification

### ISSUE THREAD

**Issue by adrien-citrus** [robcalcroft/react-native-in-app-notification#48]
My apologies for not having found my answer but how do you close the notification ?
Thank you very much for the great work, and thank you in advance for any help here :)

**Comment by robcalcroft** [comment]
Hi @adrien-citrus so at the moment there isn't an imperative way to close the notification but you can alter the duration that the notification is shown using this prop: 
![Screenshot 2021-04-26 at 10 29 00](https://user-images.githubusercontent.com/3504764/116061606-f9acbb80-a67a-11eb-8a63-6f8e956f5f3d.png)

**Comment by adrien-citrus** [comment]
Thank you for the answer @robcalcroft 👍
